experiment:
  dataset: tokyo_trails

  data_config:
    strategy: dataset
    dataset_path: ../../../../dataset/elliot_train_Tokyo.tsv

  prefiltering:
    strategy: iterative_k_core
    core: 5

  splitting:
    save_on_disk: True
    save_folder: ../../../../dataset/splitting/tokyo
    test_splitting:
      strategy: temporal_hold_out
      test_ratio: 0.2

  path_output_rec_result: ../../../../predictions/elliot_output/tokyo/result
  path_output_rec_weight: ../../../../predictions/elliot_output/tokyo/weight
  path_output_rec_performance: ../../../../predictions/elliot_output/tokyo/performance
  path_log_folder: ../../../../predictions/elliot_output/tokyo/log

  top_k: 50

  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG]
    relevance_threshold: 1

  models:
    MostPop:
      meta:
        save_recs: True

    MF:
      meta:
        save_recs: True
        save_weights: True
        verbose: True
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        validation_metric: nDCG@10
      epochs: 150
      batch_size: 1024
      factors: [8, 16, 24, 32, 48, 64, 96, 128, 192, 256]
      lr: [0.1, 0.01, 0.001, 0.0001]
      reg: [0.01, 0.001, 0.0001, 0.00001]
      early_stopping:
        patience: 8
        monitor: nDCG@10
        mode: auto
        verbose: True
        min_delta: 0.001
        rel_delta: 0.1
        baseline: 0.1
